# Site settings
title: 爱贝睿内容组件 #website title
description: > # this means to ignore newlines until "baseurl:"
  爱贝睿内容组件
url: # https://jonjia.github.io/ # the base hostname & protocol for your site
baseurl: # the sub-path of your site, e.g. /blog/

disqus_shortname:  # leave empty if you don't want comments
google_analytics: false #if set to "true" modify the google_analytycs.html, set to false otherwise

# timezone: Asia/Shanghai



# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

future: true

defaults:
  -
    scope:
      path: ""      # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: "贾文辉"
